version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: yubarta-api
    command: >
      /app/bin/wait-for-it.sh kafka:9092 -- uvicorn yubarta.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - kafka
    # env_file:
    #   - .env.ci
    environment:
      - ENV=dev
      - DATABASE_URL=postgresql://yubarta:password@postgres:5432/yubarta
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  director:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: yubarta-director
    command: watchfiles "python -m yubarta.controllers.director"
    volumes:
      - .:/app
    depends_on:
      - api
    environment:
      - DATABASE_URL=postgresql://yubarta:password@postgres:5432/yubarta
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       BUILDKIT_INLINE_CACHE: 1
  #   container_name: yubarta-worker
  #   command: python -m yubarta.controllers.coordinator.injector
  #   depends_on:
  #     - kafka
  #     - postgres
  #   environment:
  #     - DATABASE_URL=postgresql://yubarta:password@postgres:5432/yubarta
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  postgres:
    image: postgres:15
    container_name: yubarta-db
    environment:
      POSTGRES_USER: yubarta
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yubarta
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  pgdata:
