[tool.poetry]
name = "Yubarta"
version = "0.1.0"
description = ""
authors = ["Diego Fernando Rojas <hello@dfrojas.com>"]
packages = [
    { include = "yubarta"},
]

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
typer = "^0.9.0"
pyyaml = "^6.0.1"
requests = "^2.31.0"
fastapi = "^0.100.0"
uvicorn = "^0.23.1"
paramiko = "^3.2.0"
sqlalchemy = "^2.0.28"
pydantic = "^2.10.4"
greenlet = "^3.1.1"
asyncpg = "^0.28.0"
psycopg2-binary = "^2.9.9"
aiokafka = "^0.11.0"  # Downgraded to 0.11 while mockafka-py supports aiokafka 0.12
pydantic-settings = "^2.9.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
ruff = "^0.8.4"
ipdb = "^0.13.11"
watchfiles = "^1.0.5"
pytest-asyncio = "^0.26.0"
pytest-dotenv = "^0.5.2"
mockafka-py = "^0.1.63"
mypy = "^1.15.0"
types-paramiko = "^3.5.0"
types-pyyaml = "^6.0.12"
types-requests = "^2.32.0"

[tool.mypy]
strict = true
disallow_any_unimported = true

[[tool.mypy.overrides]]
module = "tests.*"
disable_error_code = "arg-type, no-untyped-call, import-untyped, union-attr"
disallow_untyped_defs = false
disallow_incomplete_defs = false

[[tool.mypy.overrides]]
# Ignore for now since still is in WIP
module = "yubarta.entrypoints.cli.*"
ignore_errors = true

[[tool.mypy.overrides]]
# Ignore for now since still is in WIP
module = "yubarta.controllers.coordinator.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "aiokafka.*"
ignore_missing_imports = true

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
line-ending = "auto"
docstring-code-line-length = "dynamic"

[tool.pytest.ini_options]
addopts = """
    --envfile=.env.ci
    --verbose
    --durations=10
"""
pythonpath = ["./src"]
testpaths = ["./tests"]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
