[tool.poetry]
name = "Yubarta"
version = "0.1.0"
description = "An application for deploying eBPF programs"
authors = ["Diego Fernando Rojas <hello@dfrojas.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/yourusername/yubarta"
repository = "https://github.com/yourusername/yubarta"
keywords = ["ebpf", "kubernetes", "api-server", "deployment"]

[tool.poetry.scripts]
yubarta-api = "yubarta.src.main:start_server"
yubarta-cli = "yubarta.cli:main"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.95.0"
pydantic = "^1.10.0"
PyYAML = "^6.0"
paramiko = "^2.11.0"
uvicorn = "^0.21.0"

[tool.poetry.dev-dependencies]
pytest = "^7.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"