target-version = "py310"

line-length = 88
indent-width = 4

[lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = []

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"__init__.py" = ["E402"]
# TODO: Enable when the files are refactored and usable.
"src/engine/service_layer/services.py" = ["E501"]
"src/engine/entrypoints/cli/commands.py" = ["E501"]
"main.py" = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

skip-magic-trailing-comma = false
line-ending = "auto"

docstring-code-line-length = "dynamic"

exclude = ["*.pyi"]
