from typing import Protocol

from yubarta.core.enums import IncidentState, StepKind, StepState
from yubarta.core.models import CommandResult, Incident, IncidentStep, NormalizedEvent, StateTransition, TriggerEvent


class CommandExecutor(Protocol):
    async def run(self, command: str, timeout: float = 60.0) -> CommandResult: ...


class IncidentRepository(Protocol):
    async def get(self, incident_id: str) -> Incident | None: ...

    async def get_or_create_active(self, target: str, incident_type: str) -> tuple[Incident, bool]: ...

    async def transition_state(
        self, incident_id: str, expected_version: int, to_state: IncidentState, reason: str = ""
    ) -> Incident: ...

    async def mark_resolved(
        self, incident_id: str, expected_version: int, resolved_by_step_id: str | None, reason: str = ""
    ) -> Incident: ...

    async def mark_failed(self, incident_id: str, expected_version: int, reason: str) -> Incident: ...

    async def add_trigger_event(self, incident_id: str, event: NormalizedEvent) -> TriggerEvent | None: ...

    async def add_step(
        self, incident_id: str, kind: StepKind, name: str, state: StepState = StepState.PENDING
    ) -> IncidentStep: ...

    async def update_step(self, step_id: str, **fields: object) -> IncidentStep: ...

    async def list_steps(self, incident_id: str) -> list[IncidentStep]: ...

    async def list_transitions(self, incident_id: str) -> list[StateTransition]: ...

    async def list_trigger_events(self, incident_id: str) -> list[TriggerEvent]: ...

    async def list_incidents(self, limit: int = 50) -> list[Incident]: ...
