from typing import Protocol
from uuid import UUID

from yubarta.config.settings import HTTPCheck
from yubarta.core.enums import IncidentState, StepKind
from yubarta.core.models import ExecutionResult, Incident, IncidentDetail, NormalizedEvent, Step


class CommandPort(Protocol):
    async def run(self, command: str, timeout: float) -> ExecutionResult: ...


class HTTPPort(Protocol):
    async def check(self, check: HTTPCheck) -> ExecutionResult: ...


class RepositoryPort(Protocol):
    async def get(self, incident_id: UUID) -> Incident | None: ...

    async def list(self, limit: int = 100, active: bool = False) -> list[Incident]: ...

    async def active_count(self) -> int: ...

    async def record_event(self, event: NormalizedEvent, incident_type: str) -> tuple[Incident | None, bool]: ...

    async def transition(self, incident: Incident, destination: IncidentState, reason: str,
                         resolved_by: UUID | None = None) -> Incident: ...

    async def start_step(self, incident_id: UUID, kind: StepKind, name: str) -> Step: ...

    async def finish_step(self, step: Step, result: ExecutionResult, skipped: bool = False) -> Step: ...

    async def interrupt_steps(self, incident_id: UUID, reason: str) -> None: ...

    async def detail(self, incident_id: UUID) -> IncidentDetail | None: ...
