from typing import Protocol, runtime_checkable

from yubarta.core.models import Alert


@runtime_checkable
class AlarmProviderInterface(Protocol):
    def configure(self, alarm: dict) -> Alert: ...

    def normalize(self, alarm: dict) -> Alert: ...

    def run(self, alarm: dict) -> Alert: ...


class AlarmStorageInterface(Protocol):
    async def add(self, alert: Alert): ...

    async def get_all(self) -> list[Alert]: ...


class AlarmMessagingInterface(Protocol):
    async def start(self): ...

    async def stop(self): ...

    async def publish(self, alert: Alert): ...
