name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install deps with Docker
      run: |
        docker compose -f docker-compose.dev.yaml build
    - name: Run tests with dependencies
      run: |
        cp .env.ci .env
        docker compose -f docker-compose.dev.yaml run --rm api poetry run pytest
